# Generated by Django 5.2.12 on 2026-03-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='advertisementimage',
            name='image',
        ),
    ]
