# Generated by Django 5.2.12 on 2026-03-09 06:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_remove_advertisement_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='featured_image',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='advertisements/'),
        ),
        migrations.AddField(
            model_name='advertisementimage',
            name='image',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='advertisement_images/'),
        ),
    ]
